[package]
name = "ascii-star-server"
version = "0.1.0"
authors = ["aticu <15schnic@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
ultrastar-txt = { git = "https://github.com/Lordakius/ultrastar-txt.git" }
